### ISSUE TITLE
Which model do the authors use to reconstruct images from ImageNet?

### ISSUE THREAD

**Issue by DengZeshuai** [hamadichihaoui/BIRD#14]
I would like to test the model on natural images, such as those from ImageNet. However, it is unclear which pre-trained model the authors used for reconstructing samples from ImageNet. Could you please provide the corresponding pre-trained model?

**Comment by hamadichihaoui** [comment]
Hi,

Sorry for the late reply. For Imagenet, we used the same openai model as the prior works https://github.com/openai/guided-diffusion

**Comment by DengZeshuai** [comment]
Thanks for your reply.

**Comment by KaishengPang** [comment]
> Thanks for your reply.

Hi DengZeshuai, I recently ran into the same issue and was wondering if you found the specific model. I've tried a few checkpoints, but none seem to work. Thank you for any help!

**Comment by iajinkyahase** [comment]
Hi @KaishengPang i also ran into same issue if you had specific model which matches please share it with me.
Thank you!

**Comment by KaishengPang** [comment]
Hi @iajinkyahase , I couldn't find the specific model either and didn't follow up later.
